### ISSUE TITLE
I download the code and remove the disabled plugins directory as normal but 1 bad thing that happened is it got this error on CONSOLE please fix as soon as possible

### ISSUE THREAD

**Issue by NguyenQuangLap** [ImagicalCorp/BetterLogin#1]
[CRITICAL]: pocketmine\utils\PluginException: "Plugin attempted to register thebigsmileXD\BetterLogin\Main while not enabled" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 700

**Comment by thebigsmileXD** [comment]
BetterLogin isn't finished in ANY way.

**Comment by NguyenQuangLap** [comment]
@thebigsmileXD how to fix ?

**Comment by NguyenQuangLap** [comment]
@thebigsmileXD Data can help me find the plugin anti spam plugin and not the chat from not good? I could not install ChatProtection

**Comment by keithkfng** [comment]
Don't you see the README file? It's IN-DEV.

**Comment by thebigsmileXD** [comment]
Its not even In-Dev anymore. I gave up for IM

**Comment by keithkfng** [comment]
That's nice...

**Comment by thebigsmileXD** [comment]
Oh.. I know what i did. the plugin disables itself ob start. So you don't get any problems on your server.
